[package]
name = "test_play"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
librespot = "0.3.1"
tokio = "1.16.1"
sha1 = "0.10.0"
hex = "0.4.3"
futures = "0.3.21"
